activation: !!python/name:torch.nn.modules.activation.SiLU ''
beta: 1.0
condition_dim: 8
decoder_layers:
- 64
- 64
- 64
- 32
- 32
- 32
encoder_layers:
- 32
- 32
- 32
- 64
- 64
- 64
input_dim: 6
latent_dim: 128
learning_rate: 0.001
output_activation: null
residual: true
use_batchnorm: true
