##### Parameters used for area a #####
# some parameters are reused for area b
# Training settings
train_flag: True
data_name: "floor4_sf_11_finetune_dataset.pth"
save_model_name: "RGM_pretrain.ckpt"
frac_for_valid: 0.05
frac_for_test: 0.25

# Parameters for location classifier
classifier_input_channels: 2
classifier_hidden_input_len: 4
num_locs: 21
n_layers: 3
input_dim: 6
hidden_dim: 128
dropout_pra: 0.1
learning_rate: 0.0001
num_epochs: 100
batch_size: 256
location_vector_name: "location_vector_v2.csv"
config: "configs/finetune.yml"

##### New parameters for pre-training rgm #####
signal_feature_dim: 16           # 因为inputdim太小，做一个线性变化为高纬度，组成channels*signal_feature_dim
loc_dim: 8             # for location vector
num_timesteps: 1000
schedule: "linear"    # cosine, linear, quadratic, sigmoid
data_channels: 2      # number of data channels（unet卷积层通道数）
channel_dimension_scale: [1, 2, 4,8,16]
num_epochs_rgm: 200
batch_size_rgm: 256
learning_rate_rgm: 0.001
rgm_pretrain_path: "1_pretrained_rgm.ckpt"


##### New parameters for fine-tuning rGM #####
data_name_ft: "floor4_sf_11_test_dataset.pth"
ratios_locs: 0.25
data_name_fake: "floor4_v3.pth"
save_model_name_fake: "classifier_fingerprint.ckpt"
num_epochs_rgm_ft: 100
rgm_fine_tune_path: "2_finetuned_rgm.ckpt"


