##### Parameters used for area a #####
# some parameters are reused for area b
# Training settings
train_flag: True
data_name: "floor4_sf_11_pretrain_dataset.pth"
frac_for_valid: 0.05
frac_for_test: 0.25

# Parameters for location classifier
classifier_input_channels: 2
classifier_hidden_input_len: 4
num_locs: 21
n_layers: 3
input_dim: 6
hidden_dim: 128
dropout_pra: 0.1
learning_rate: 0.0001
num_epochs: 100
batch_size: 256
location_vector_name: "location_vector_v3.csv"
config: "configs/finetune.yml"

##### New parameters for pre-training rgm #####
signal_feature_dim: 4           # 因为inputdim太小，做一个线性变化为高纬度，组成channels*signal_feature_dim
loc_dim: 5             # for location vector x\y\distance\sf\tp
num_timesteps: 1000
schedule: "linear"    # cosine, linear, quadratic, sigmoid
data_channels: 2      # number of data channels（unet卷积层通道数）
sf_parameter_path: "model\\v1\\output\\sf_parameters.csv"
channel_dimension_scale: [1, 2, 4,8]
num_epochs_rgm: 100
batch_size_rgm: 128
learning_rate_rgm: 0.001
rgm_pretrain_path: "rgm_floor3_sf_11_pretrained.ckpt"


##### New parameters for fine-tuning rGM #####

data_name_ft: "floor4_sf_11_pretrain.pth" #input文件夹下
data_name_fake: "floor4_sf_11_fake.pth" 
ratios_locs: 0.25
save_model_name_fake: "classifier_fingerprint.ckpt"
num_epochs_rgm_ft: 70
rgm_fine_tune_path: "floor4_sf_11_finetuned_rgm.ckpt"


