##### Parameters used for area a #####
# some parameters are reused for area b
# Training settings
gateway_X: 598
gateway_Y: 474
# Parameters for location classifier
configs: "location_vector.yml"
location_vector_name: "location_vector_v3.csv"
distance_scale: 0.123

